# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='left',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='top',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
