# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-26 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='location',
        ),
        migrations.AddField(
            model_name='seat',
            name='seatgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.SeatGroup'),
        ),
    ]
