# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20161126_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatgroup',
            name='left',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='seatgroup',
            name='top',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
