# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_date',
            new_name='Book_AddDate',
        ),
        migrations.RenameModel(
            old_name='search_date',
            new_name='Book_SearchDate',
        ),
    ]
