# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 23:48
from __future__ import unicode_literals

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('mark', models.CharField(max_length=128)),
                ('sideImage', models.ImageField(default=None, null=True, upload_to=book.models.UploadImage)),
            ],
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_mark', models.CharField(max_length=128)),
                ('upper_mark', models.CharField(max_length=128)),
                ('mapImage', models.ImageField(default=None, null=True, upload_to=book.models.UploadImage)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Bookshelf'),
        ),
    ]
