# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
