# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='num',
            new_name='cid',
        ),
    ]
