# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20160412_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='bookshelf',
        ),
    ]
