# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20160417_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='mapImage',
        ),
        migrations.AlterField(
            model_name='book',
            name='sideImage',
            field=models.ImageField(default=None, null=True, upload_to='booksideimage'),
        ),
    ]
