# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-26 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20161125_1431'),
        ('book', '0007_auto_20160601_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
